version: '3'

services:
  app:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - REDIS_STREAM_NEW_HOTDEALS_KEY=${REDIS_STREAM_NEW_HOTDEALS_KEY}
      - REDIS_STREAM_NEW_HOTDEALS_PARTITIONS=${REDIS_STREAM_NEW_HOTDEALS_PARTITIONS}
      - REDIS_STREAM_CONSUMER_GROUP=${REDIS_STREAM_CONSUMER_GROUP}
      - REDIS_STREAM_CONSUMER_NAME=${REDIS_STREAM_CONSUMER_NAME}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
